#!/usr/bin/env bash
# Builds crumb-relay for a Linux target with the distribution's GCC cross toolchains (CI runs it
# on Ubuntu 22.04; `packages` lists what to apt-get). BoringSSL, under wreq, is compiled from
# source by CMake, so the C and C++ compilers and clang's sysroot are set per target.
#
#   cross-build.sh packages TARGET        apt packages the target needs, space-separated
#   cross-build.sh build TARGET [ARGS..]  cargo build --locked -p crumb-relay --target TARGET ARGS
#
# Used by .github/workflows/relay.yml (releases, --release) and pr.yml (a quick check).
set -euo pipefail

cmd=${1:?packages or build}
target=${2:?target triple}
shift 2

case $target in
  x86_64-unknown-linux-gnu)
    packages=""
    gcc=gcc gxx=g++ sysroot=""
    ;;
  aarch64-unknown-linux-gnu)
    packages="gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross"
    gcc=aarch64-linux-gnu-gcc gxx=aarch64-linux-gnu-g++ sysroot=/usr/aarch64-linux-gnu
    ;;
  armv7-unknown-linux-gnueabihf)
    packages="gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf libc6-dev-armhf-cross"
    gcc=arm-linux-gnueabihf-gcc gxx=arm-linux-gnueabihf-g++ sysroot=/usr/arm-linux-gnueabihf
    ;;
  *)
    echo "unknown target $target" >&2
    exit 2
    ;;
esac

case $cmd in
  packages) echo "$packages" ;;
  build)
    # Cargo and the cc crate read these per target: TRIPLE_WITH_UNDERSCORES
    triple=${target//-/_}
    upper=$(tr '[:lower:]' '[:upper:]' <<<"$triple")
    export "CC_$triple=$gcc" "CXX_$triple=$gxx"
    export "CARGO_TARGET_${upper}_LINKER=$gcc"
    if [[ -n $sysroot ]]; then
      # The bindings for BoringSSL are generated by clang, which needs the target's headers
      export "BINDGEN_EXTRA_CLANG_ARGS_$triple=--sysroot=$sysroot -I$sysroot/include"
    fi
    cargo build --locked -p crumb-relay --target "$target" "$@"
    ;;
  *)
    echo "unknown command $cmd" >&2
    exit 2
    ;;
esac
