//! Display helpers: the plain-text and Markdown renderings of a recipe or cookbook,
//! and the URL helpers that decide what may be shown as a link. Ported from
//! `web/src/lib/format.ts` and `web/src/lib/recipe.ts`; parity fixtures are in
//! `tests/fixtures/format.json`, generated by `tests/fixtures/gen-format.ts`.

use crate::model::{Recipe, Section, is_valid_url};

/// Plain-text/Markdown rendering used for "copy recipe" and the Claude connector.
pub fn recipe_to_markdown(r: &Recipe) -> String {
    let meta: Vec<String> = [
        ("Prep", &r.prep_time),
        ("Cook", &r.cook_time),
        ("Additional", &r.freeze_time),
        ("Total", &r.total_time),
        ("Yield", &r.recipe_yield),
        ("Category", &r.recipe_category),
        ("Cuisine", &r.recipe_cuisine),
        ("By", &r.author),
    ]
    .iter()
    .filter_map(|(label, v)| {
        v.as_deref()
            .filter(|v| !v.is_empty())
            .map(|v| format!("{label}: {v}"))
    })
    .collect();

    let mut out = vec![format!("# {}", r.title)];
    if let Some(d) = r.description.as_deref().filter(|d| !d.is_empty()) {
        out.extend(["".into(), d.to_string()]);
    }
    if !meta.is_empty() {
        out.extend(["".into(), meta.join(" · ")]);
    }

    out.extend(["".into(), "## Ingredients".into()]);
    for s in &r.ingredients {
        if let Some(name) = s.name.as_deref().filter(|n| !n.is_empty()) {
            out.extend(["".into(), format!("### {name}")]);
        }
        out.extend(s.items.iter().map(|i| format!("- {i}")));
    }

    out.extend(["".into(), "## Instructions".into()]);
    let mut step = 0;
    for s in &r.instructions {
        if let Some(name) = s.name.as_deref().filter(|n| !n.is_empty()) {
            out.extend(["".into(), format!("### {name}")]);
        }
        for item in &s.items {
            step += 1;
            out.push(format!("{step}. {item}"));
        }
    }

    if let Some(n) = r.notes.as_deref().filter(|n| !n.is_empty()) {
        out.extend(["".into(), "## Notes".into(), n.to_string()]);
    }
    if let Some(u) = crate::source::source_url(r) {
        out.extend(["".into(), format!("Source: {u}")]);
    }
    out.join("\n")
}

/// Plain text for pasting into a message: the title, "•" ingredients under their section
/// names, numbered steps, and the share link when there is one. Not Markdown.
pub fn recipe_to_text(r: &Recipe, link: Option<&str>) -> String {
    let mut out = vec![r.title.clone()];

    let ingredients: Vec<&Section> = r
        .ingredients
        .iter()
        .filter(|s| !s.items.is_empty())
        .collect();
    if !ingredients.is_empty() {
        out.extend(["".into(), "Ingredients".into()]);
        for s in ingredients {
            if let Some(name) = s.name.as_deref().filter(|n| !n.is_empty()) {
                out.extend(["".into(), name.to_string()]);
            }
            out.extend(s.items.iter().map(|i| format!("• {i}")));
        }
    }

    let steps: Vec<&Section> = r
        .instructions
        .iter()
        .filter(|s| !s.items.is_empty())
        .collect();
    if !steps.is_empty() {
        out.extend(["".into(), "Method".into()]);
        let mut n = 0;
        for s in steps {
            if let Some(name) = s.name.as_deref().filter(|n| !n.is_empty()) {
                out.extend(["".into(), name.to_string()]);
            }
            for item in &s.items {
                n += 1;
                out.push(format!("{n}. {item}"));
            }
        }
    }

    if let Some(link) = link.filter(|l| !l.is_empty()) {
        out.extend(["".into(), link.to_string()]);
    }
    out.join("\n")
}

/// A cookbook as plain text: its name, its recipes' titles and the link.
pub fn book_to_text(name: &str, titles: &[&str], link: Option<&str>) -> String {
    let mut out = vec![name.to_string()];
    if !titles.is_empty() {
        out.push(String::new());
        out.extend(titles.iter().map(|t| format!("• {t}")));
    }
    if let Some(link) = link.filter(|l| !l.is_empty()) {
        out.extend([String::new(), link.to_string()]);
    }
    out.join("\n")
}

/// The toast after saving another Crumb's shared cookbook: "Added 12 recipes to Weeknight
/// dinners", with ", 1 skipped" when some couldn't be saved.
pub fn book_imported_title(
    name: &str,
    added: usize,
    duplicates: usize,
    skipped: Option<usize>,
) -> String {
    // A zero count is the same as none ("if (b.skipped)").
    let skipped = skipped.filter(|n| *n > 0);
    let skipped_note = skipped
        .map(|n| format!(", {n} skipped"))
        .unwrap_or_default();
    if duplicates > 0 && added == 0 {
        return format!("Already in your recipes, now in {name}{skipped_note}");
    }
    if added > 0 || skipped.is_some() {
        return format!("Added {} to {name}{skipped_note}", count(added));
    }
    format!("Added {name}, an empty cookbook")
}

fn count(n: usize) -> String {
    format!("{n} recipe{}", if n == 1 { "" } else { "s" })
}

/// The category and cuisine line under a recipe's title.
pub fn kicker(category: Option<&str>, cuisine: Option<&str>) -> String {
    [category, cuisine]
        .into_iter()
        .flatten()
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join(" · ")
}

/// `url` when it's an http(s) address, else null: never link a `javascript:` or `data:` URL.
pub fn web_link(url: Option<&str>) -> Option<String> {
    let url = url?;
    if is_valid_url(url) {
        Some(url.to_string())
    } else {
        None
    }
}

/// An http(s) address's host without `www.`; null for anything else.
pub fn host_of(url: Option<&str>) -> Option<String> {
    let link = web_link(url)?;
    let host = url::Url::parse(&link).ok()?.host_str()?.to_string();
    Some(host.strip_prefix("www.").unwrap_or(&host).to_string())
}
