//! Ingredient-line parsing, formatting and scaling, ported from the frontend's
//! `web/src/lib/ingredients.ts`.
//!
//! `"1 1/2 cups flour, sifted"` becomes
//! `{ quantity: 1.5, unit: "cup", name: "flour", prep: "sifted" }`; the same
//! module formats scaled quantities back as Unicode fractions, decides what
//! vessel each line of mise en place needs, and finds the times a step mentions
//! for cook mode's suggested timer (with the timer's nudges and wording).
//!
//! The TypeScript remains the source of truth. The port is checked case for case
//! against fixtures generated by `tests/fixtures/gen-ingredients.ts`
//! (`tests/ingredients_parity.rs`). Several deliberate details exist only to
//! match JavaScript exactly:
//!
//! - `format_quantity` follows `Number.prototype.toFixed` for its rounding, which
//!   agrees with Rust's `{:.n}` formatting for the values this code produces.
//! - Word boundaries use `(?-u:\b)` (ASCII) because JavaScript's `\b` is based on
//!   ASCII `\w` even without the `u` flag; `\s` stays Unicode, as in JavaScript.
//! - Unit alternations keep the same order and case sensitivity as the TS table.

use std::sync::LazyLock;

use regex::Regex;
use serde::{Deserialize, Serialize};

/// Unicode fractions the parser understands, and that `format_quantity` emits.
const UNICODE_FRACTIONS: [(char, f64); 12] = [
    ('¼', 0.25),
    ('½', 0.5),
    ('¾', 0.75),
    ('⅓', 1.0 / 3.0),
    ('⅔', 2.0 / 3.0),
    ('⅕', 0.2),
    ('⅙', 1.0 / 6.0),
    ('⅚', 5.0 / 6.0),
    ('⅛', 0.125),
    ('⅜', 0.375),
    ('⅝', 0.625),
    ('⅞', 0.875),
];

const FRACTION_CHARS: &str = "¼½¾⅓⅔⅕⅙⅚⅛⅜⅝⅞";

/// Canonical unit → aliases. Order matters for matching (longer first within the
/// regex) and for the exact/lowercase lookup, exactly as in the TS `UNITS` table.
const UNITS: [(&str, &[&str]); 21] = [
    ("tsp", &["teaspoons", "teaspoon", "tsps", "tsp", "t"]),
    (
        "tbsp",
        &[
            "tablespoons",
            "tablespoon",
            "tbsps",
            "tbsp",
            "tbs",
            "tbl",
            "T",
        ],
    ),
    ("cup", &["cups", "cup", "c"]),
    (
        "ml",
        &[
            "milliliters",
            "millilitres",
            "milliliter",
            "millilitre",
            "ml",
            "mL",
        ],
    ),
    ("l", &["liters", "litres", "liter", "litre", "l", "L"]),
    (
        "fl oz",
        &["fluid ounces", "fluid ounce", "fl oz", "fl. oz."],
    ),
    ("oz", &["ounces", "ounce", "oz"]),
    ("lb", &["pounds", "pound", "lbs", "lb"]),
    ("g", &["grams", "gram", "g", "gr"]),
    ("kg", &["kilograms", "kilogram", "kg"]),
    ("pinch", &["pinches", "pinch"]),
    ("dash", &["dashes", "dash"]),
    ("clove", &["cloves", "clove"]),
    ("can", &["cans", "can", "tins", "tin"]),
    ("stick", &["sticks", "stick"]),
    ("slice", &["slices", "slice"]),
    ("bunch", &["bunches", "bunch"]),
    ("sprig", &["sprigs", "sprig"]),
    ("handful", &["handfuls", "handful"]),
    ("piece", &["pieces", "piece"]),
    (
        "package",
        &["packages", "package", "packets", "packet", "pkg"],
    ),
];

/// The `parseNumber` number pattern. `[0-9]` rather than `\d` so the match is
/// ASCII, as in a JavaScript regex without the `u` flag.
const NUMBER: &str = r"(?:[0-9]+\s+[0-9]+/[0-9]+|[0-9]+/[0-9]+|[0-9]*\.[0-9]+|[0-9]+(?:\s*[¼½¾⅓⅔⅕⅙⅚⅛⅜⅝⅞])?|[¼½¾⅓⅔⅕⅙⅚⅛⅜⅝⅞])";

/// Unit aliases in matching order: longest first, stable on ties (the TS
/// `[...aliasToUnit.keys()].sort((a, b) => b.length - a.length)`).
static UNIT_PATTERN: LazyLock<String> = LazyLock::new(|| {
    let mut aliases: Vec<&str> = UNITS
        .iter()
        .flat_map(|(_, aliases)| aliases.iter().copied())
        .collect();
    aliases.sort_by_key(|alias| std::cmp::Reverse(alias.len()));
    aliases
        .iter()
        .map(|alias| regex::escape(alias))
        .collect::<Vec<_>>()
        .join("|")
});

/// Word units only: lowercase-only aliases of three or more letters, so "T" or
/// "c" at the start of a name is not read as a unit.
static BARE_UNIT_PATTERN: LazyLock<String> = LazyLock::new(|| {
    let mut aliases: Vec<&str> = UNITS
        .iter()
        .flat_map(|(_, aliases)| aliases.iter().copied())
        .filter(|a| a.len() >= 3 && a.chars().all(|c| c.is_ascii_lowercase()))
        .collect();
    aliases.sort_by_key(|alias| std::cmp::Reverse(alias.len()));
    aliases.join("|")
});

static LEADING: LazyLock<Regex> = LazyLock::new(|| {
    let unit = UNIT_PATTERN.as_str();
    // The TS uses `\.?(?=\s|$|,)` to stop short aliases ("g") matching the start
    // of a longer word ("garlic"). Rust's regex has no look-around, so the
    // delimiter is captured and put back into the rest when it is a comma; a
    // whitespace delimiter is the same whitespace the TS `\s*` would swallow.
    Regex::new(&format!(
        r"^\s*(?:about|approx\.?|~)?\s*({NUMBER})(?:\s*(?:-|–|to)\s*({NUMBER}))?\s*(?:({unit})\.?(\s|,|$)(\s*))?(?:of\s+)?(.*)$"
    ))
    .unwrap()
});

static BARE_UNIT: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(&format!(
        r"(?i)^({})\s+(?:of\s+)?(.+)$",
        BARE_UNIT_PATTERN.as_str()
    ))
    .unwrap()
});

static WORD_QUANTITY: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?i)^\s*(a|an|one|a few|a couple of|some)\s+(.*)$").unwrap());

static WORD_UNIT: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(&format!(r"^({})\s+(?:of\s+)?(.*)$", UNIT_PATTERN.as_str())).unwrap()
});

/// Checkbox and bullet glyphs some recipe sites put in front of every line.
static GLYPHS: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^(?:[▢☐□■◻◽◾▪▫☑☒✓✔✅•◦●○∙]\s*|\*\s+)+").unwrap());

static PARENTHETICAL: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^(.*?)\s*\(([^)]*)\)\s*(.*)$").unwrap());

static UNICODE_NUMBER: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(&format!(r"^([0-9]+)?\s*([{FRACTION_CHARS}])$")).unwrap());

static MIXED_NUMBER: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^([0-9]+)\s+([0-9]+)/([0-9]+)$").unwrap());

static FRACTION_NUMBER: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"^([0-9]+)/([0-9]+)$").unwrap());

static SCALE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(&format!(
        r"^(\s*(?:about|approx\.?|~)?\s*)({})(?:(\s*(?:-|–|to)\s*)({}))?",
        NUMBER, NUMBER
    ))
    .unwrap()
});

// ─── Mise en place patterns ────────────────────────────────────────────────

static TO_TASTE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)(?-u:\b)(to taste|as needed|for serving|for garnish|optional|for frying|for greasing)(?-u:\b)",
    )
    .unwrap()
});

static WHOLE_PRODUCE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)(?-u:\b)(onions?|shallots?|carrots?|potato(?:es)?|tomato(?:es)?|(?:bell|sweet|red|green|yellow|orange|chil[ei]|jalape[nñ]o) peppers?|jalape[nñ]os?|zucchini|courgettes?|cucumbers?|apples?|lemons?|limes?|oranges?|avocados?|chicken|beef|pork|lamb|fish|salmon|steaks?|breasts?|thighs?|fillets?|cabbage|cauliflower|broccoli|squash|eggplants?|aubergines?|leeks?|celery|mushrooms?|bananas?|mango(?:es)?|mince|ground (?:beef|pork|turkey)|shrimp|prawns?|tofu)(?-u:\b)",
    )
    .unwrap()
});

/// Knife words → the task name. The keys are also the `CUTTING` alternation, in
/// this order.
const CUT_TASKS: [(&str, &str); 16] = [
    ("chopped", "chop"),
    ("diced", "dice"),
    ("minced", "mince"),
    ("sliced", "slice"),
    ("grated", "grate"),
    ("julienned", "julienne"),
    ("cubed", "cube"),
    ("crushed", "crush"),
    ("peeled", "peel"),
    ("halved", "halve"),
    ("quartered", "quarter"),
    ("shredded", "shred"),
    ("trimmed", "trim"),
    ("zested", "zest"),
    ("juiced", "juice"),
    ("cut", "cut"),
];

static CUTTING: LazyLock<Regex> = LazyLock::new(|| {
    let words = CUT_TASKS
        .iter()
        .map(|(word, _)| *word)
        .collect::<Vec<_>>()
        .join("|");
    Regex::new(&format!(r"(?i)(?-u:\b)({words})(?-u:\b)")).unwrap()
});

static PANTRY: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(
        r"(?i)(?-u:\b)(powder|broth|stock|bouillon|paste|pur[eé]e|sauce|ketchup|juice|flakes|extract|seasoning|soup|granules|canned|tinned)(?-u:\b)",
    )
    .unwrap()
});

static CUT_TOMATOES: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?i)(?-u:\b)(?:crushed|diced|chopped|stewed) tomato(?:es)?(?-u:\b)").unwrap()
});

static CONTAINER: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?i)(?-u:\b)(cans?|tins?|canned|tinned|jars?|cartons?)(?-u:\b)").unwrap()
});

static JUICE_OF: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?i)(?-u:\b)juice (?:of|from)(?-u:\b)").unwrap());

static DIGITS: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"[0-9]+").unwrap());

const ML_PER_UNIT: [(&str, f64); 18] = [
    ("tsp", 5.0),
    ("tbsp", 15.0),
    ("cup", 240.0),
    ("ml", 1.0),
    ("l", 1000.0),
    ("fl oz", 30.0),
    ("oz", 28.0),
    ("lb", 450.0),
    ("g", 1.0),
    ("kg", 1000.0),
    ("pinch", 0.5),
    ("dash", 0.6),
    ("clove", 6.0),
    ("can", 400.0),
    ("stick", 115.0),
    ("handful", 40.0),
    ("bunch", 150.0),
    ("sprig", 2.0),
];

const MEASURED: [&str; 11] = [
    "tsp", "tbsp", "cup", "ml", "l", "fl oz", "oz", "lb", "g", "kg", "can",
];

const COUNTABLE: [&str; 9] = [
    "cup", "clove", "can", "stick", "slice", "sprig", "handful", "piece", "package",
];

const ES_PLURAL: [&str; 3] = ["pinch", "dash", "bunch"];

const BOARD_TASKS: [&str; 11] = [
    "chop", "dice", "mince", "slice", "julienne", "cube", "halve", "quarter", "trim", "peel", "cut",
];

const PIECES: [&str; 7] = [
    "clove", "stick", "bunch", "sprig", "piece", "slice", "handful",
];

// ─── Types ─────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ParsedIngredient {
    pub raw: String,
    pub quantity: Option<f64>,
    pub quantity_max: Option<f64>,
    pub unit: Option<String>,
    pub name: String,
    pub prep: Option<String>,
}

impl ParsedIngredient {
    fn new(
        raw: &str,
        quantity: Option<f64>,
        quantity_max: Option<f64>,
        unit: Option<String>,
        name: String,
        prep: Option<String>,
    ) -> Self {
        Self {
            raw: raw.to_string(),
            quantity,
            quantity_max,
            unit,
            name,
            prep,
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum Vessel {
    Pinch,
    Ramekin,
    Small,
    Medium,
    Large,
    Board,
    Jar,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MiseItem {
    pub raw: String,
    pub quantity: Option<f64>,
    pub quantity_max: Option<f64>,
    pub unit: Option<String>,
    pub name: String,
    pub prep: Option<String>,
    pub vessel: Vessel,
    /// Rough volume in ml, when it can be estimated.
    pub volume: Option<f64>,
    /// A short prep instruction, e.g. "dice".
    pub task: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Timer {
    pub label: String,
    pub seconds: u32,
}

// ─── Number parsing ────────────────────────────────────────────────────────

fn unicode_fraction(c: char) -> Option<f64> {
    UNICODE_FRACTIONS
        .iter()
        .find(|(glyph, _)| *glyph == c)
        .map(|(_, value)| *value)
}

fn unit_for(alias: &str) -> Option<&'static str> {
    UNITS
        .iter()
        .find(|(_, aliases)| aliases.contains(&alias))
        .map(|(unit, _)| *unit)
        .or_else(|| {
            let lower = alias.to_lowercase();
            UNITS
                .iter()
                .find(|(_, aliases)| aliases.contains(&lower.as_str()))
                .map(|(unit, _)| *unit)
        })
}

/// Parses the quantity at the start of an ingredient line ("1", "1/2", "1 1/2",
/// "1½"). `None` for anything that isn't a finite number.
pub fn parse_number(value: &str) -> Option<f64> {
    let v = value.trim();
    if v.is_empty() {
        return None;
    }
    if let Some(c) = UNICODE_NUMBER.captures(v) {
        let whole = c
            .get(1)
            .and_then(|g| g.as_str().parse::<f64>().ok())
            .unwrap_or(0.0);
        let frac = unicode_fraction(c[2].chars().next().unwrap()).unwrap();
        return Some(whole + frac);
    }
    if let Some(c) = MIXED_NUMBER.captures(v) {
        let whole: f64 = c[1].parse().unwrap();
        let num: f64 = c[2].parse().unwrap();
        let den: f64 = c[3].parse().unwrap();
        return Some(whole + num / den);
    }
    if let Some(c) = FRACTION_NUMBER.captures(v) {
        let num: f64 = c[1].parse().unwrap();
        let den: f64 = c[2].parse().unwrap();
        if den == 0.0 {
            return None;
        }
        return Some(num / den);
    }
    v.parse::<f64>().ok().filter(|n| n.is_finite())
}

// ─── Ingredient parsing ────────────────────────────────────────────────────

fn split_prep(rest: &str) -> (String, Option<String>) {
    let mut name = rest.to_string();
    let mut prep: Option<String> = None;
    if let Some(paren) = PARENTHETICAL.captures(rest) {
        name = format!("{} {}", &paren[1], &paren[3]).trim().to_string();
        prep = Some(paren[2].trim().to_string()).filter(|s| !s.is_empty());
    }
    if let Some(comma) = name.find(',')
        && comma > 0
    {
        let after = name[comma + 1..].trim().to_string();
        name = name[..comma].trim().to_string();
        prep = Some(
            [after, prep.unwrap_or_default()]
                .into_iter()
                .filter(|s| !s.is_empty())
                .collect::<Vec<_>>()
                .join(", "),
        )
        .filter(|s| !s.is_empty());
    }
    (name.trim().to_string(), prep)
}

/// Parses one ingredient line into quantity, unit, name and prep.
pub fn parse_ingredient(raw: &str) -> ParsedIngredient {
    let collapsed = raw.split_whitespace().collect::<Vec<_>>().join(" ");
    let text = GLYPHS.replace(&collapsed, "").to_string();

    if let Some(m) = LEADING.captures(&text) {
        let mut rest = m[6].to_string();
        if m.get(4).is_some_and(|d| d.as_str() == ",") {
            rest = format!(",{}{}", m.get(5).map_or("", |g| g.as_str()), rest);
        }
        let (split_name, split_prep) = split_prep(&rest);
        let mut unit = m.get(3).and_then(|g| unit_for(g.as_str()));
        let mut name = split_name;
        if unit.is_none()
            && let Some(after) = BARE_UNIT.captures(&name)
        {
            unit = unit_for(&after[1].to_lowercase());
            name = after[2].to_string();
        }
        let name = if name.is_empty() { text.clone() } else { name };
        return ParsedIngredient::new(
            raw,
            parse_number(&m[1]),
            m.get(2).and_then(|g| parse_number(g.as_str())),
            unit.map(str::to_string),
            name,
            split_prep,
        );
    }

    if let Some(bare) = BARE_UNIT.captures(&text) {
        let (name, prep) = split_prep(&bare[2]);
        return ParsedIngredient::new(
            raw,
            Some(1.0),
            None,
            unit_for(&bare[1].to_lowercase()).map(str::to_string),
            name,
            prep,
        );
    }

    if let Some(w) = WORD_QUANTITY.captures(&text) {
        let (name, prep) = split_prep(&w[2]);
        let word = w[1].to_lowercase();
        let quantity = if word == "a" || word == "an" || word == "one" {
            Some(1.0)
        } else {
            None
        };
        if let Some(unit_match) = WORD_UNIT.captures(&name) {
            return ParsedIngredient::new(
                raw,
                quantity,
                None,
                unit_for(&unit_match[1]).map(str::to_string),
                unit_match[2].to_string(),
                prep,
            );
        }
        return ParsedIngredient::new(raw, quantity, None, None, name, prep);
    }

    let (name, prep) = split_prep(&text);
    ParsedIngredient::new(raw, None, None, None, name, prep)
}

// ─── Formatting & scaling ──────────────────────────────────────────────────

/// Eighths, sixths, quarters, thirds and halves, in the order the TS looks them
/// up; each is accepted when it is within 0.02 of the fractional part.
const NICE_FRACTIONS: [(f64, &str); 11] = [
    (0.125, "⅛"),
    (1.0 / 6.0, "⅙"),
    (0.25, "¼"),
    (1.0 / 3.0, "⅓"),
    (0.375, "⅜"),
    (0.5, "½"),
    (0.625, "⅝"),
    (2.0 / 3.0, "⅔"),
    (0.75, "¾"),
    (5.0 / 6.0, "⅚"),
    (0.875, "⅞"),
];

/// Strips trailing zeros and a dot left behind by `toFixed`, like
/// `String.prototype.replace(/\.?0+$/, "")`.
fn strip_trailing_zeros(s: &str) -> String {
    let trimmed = s.trim_end_matches('0');
    trimmed.strip_suffix('.').unwrap_or(trimmed).to_string()
}

/// Formats a quantity the way the scaler prints it: Unicode fractions for the
/// nice ones, one decimal otherwise, whole numbers for ten and above.
pub fn format_quantity(n: f64) -> String {
    if n >= 10.0 {
        return format!("{}", n.round());
    }
    let whole = n.floor();
    let frac = n - whole;
    if frac < 0.06 {
        if whole != 0.0 {
            return format!("{}", whole);
        }
        return strip_trailing_zeros(&format!("{n:.2}"));
    }
    if frac > 0.94 {
        return format!("{}", whole + 1.0);
    }
    if let Some((_, glyph)) = NICE_FRACTIONS.iter().find(|(v, _)| (v - frac).abs() < 0.02) {
        return if whole != 0.0 {
            format!("{} {glyph}", whole)
        } else {
            (*glyph).to_string()
        };
    }
    let fixed = format!("{n:.1}");
    fixed.strip_suffix(".0").unwrap_or(&fixed).to_string()
}

/// Scales the leading quantity of an ingredient line, keeping the rest verbatim.
pub fn scale_ingredient(raw: &str, factor: f64) -> String {
    if factor == 1.0 {
        return raw.to_string();
    }
    let Some(m) = SCALE.captures(raw) else {
        return raw.to_string();
    };
    let Some(a) = parse_number(&m[2]) else {
        return raw.to_string();
    };
    let mut scaled = format_quantity(a * factor);
    if let Some(b) = m.get(4).and_then(|g| parse_number(g.as_str())) {
        scaled.push_str(&m[3]);
        scaled.push_str(&format_quantity(b * factor));
    }
    let end = m.get(0).map_or(0, |g| g.end());
    format!("{}{scaled}{}", &m[1], &raw[end..])
}

/// `"3 clove"` → `"3 cloves"` for count-like units; abbreviations stay as they are.
pub fn plural_unit(unit: &str, quantity: f64) -> String {
    if quantity <= 1.0 {
        return unit.to_string();
    }
    if COUNTABLE.contains(&unit) {
        return format!("{unit}s");
    }
    if ES_PLURAL.contains(&unit) {
        return format!("{unit}es");
    }
    unit.to_string()
}

// ─── Mise en place ─────────────────────────────────────────────────────────

fn vessel_for(volume: f64) -> Vessel {
    if volume <= 3.0 {
        Vessel::Pinch
    } else if volume <= 35.0 {
        Vessel::Ramekin
    } else if volume <= 150.0 {
        Vessel::Small
    } else if volume <= 500.0 {
        Vessel::Medium
    } else {
        Vessel::Large
    }
}

fn cut_task(cut: &str) -> Option<&'static str> {
    CUT_TASKS
        .iter()
        .find(|(word, _)| *word == cut)
        .map(|(_, task)| *task)
}

fn ml_per_unit(unit: &str) -> Option<f64> {
    ML_PER_UNIT
        .iter()
        .find(|(name, _)| *name == unit)
        .map(|(_, ml)| *ml)
}

fn mise_item(
    p: ParsedIngredient,
    vessel: Vessel,
    volume: Option<f64>,
    task: Option<String>,
) -> MiseItem {
    MiseItem {
        raw: p.raw,
        quantity: p.quantity,
        quantity_max: p.quantity_max,
        unit: p.unit,
        name: p.name,
        prep: p.prep,
        vessel,
        volume,
        task,
    }
}

/// Decides what to prep each ingredient into: a pinch bowl, ramekin, bowl, board
/// or jar, and gives the prep task when there is one.
pub fn mise_en_place(lines: &[&str]) -> Vec<MiseItem> {
    lines
        .iter()
        .map(|line| {
            let p = parse_ingredient(line);
            if JUICE_OF.is_match(line) {
                let count = p.quantity_max.or(p.quantity).unwrap_or_else(|| {
                    DIGITS
                        .find(line)
                        .and_then(|m| m.as_str().parse::<f64>().ok())
                        .unwrap_or(1.0)
                });
                let vessel = if count <= 1.0 {
                    Vessel::Ramekin
                } else {
                    Vessel::Small
                };
                return mise_item(p, vessel, None, Some("juice".to_string()));
            }
            let pantry = PANTRY.is_match(&p.name)
                || (CUT_TOMATOES.is_match(&p.name)
                    && (CONTAINER.is_match(line)
                        || p.unit.as_deref().is_some_and(|u| MEASURED.contains(&u))));
            let produce = !pantry && WHOLE_PRODUCE.is_match(&p.name);
            let prep_text = match &p.prep {
                Some(prep) => format!("{prep} {line}"),
                None => (*line).to_string(),
            };
            let cut = if pantry {
                None
            } else {
                CUTTING.captures(&prep_text).map(|c| c[1].to_lowercase())
            };
            let task = cut.as_deref().and_then(cut_task);

            if p.quantity.is_none() && TO_TASTE.is_match(line) {
                return mise_item(p, Vessel::Jar, None, task.map(str::to_string));
            }
            let per_unit = p.unit.as_deref().and_then(ml_per_unit);
            let by_weight = matches!(p.unit.as_deref(), Some("g" | "kg" | "lb" | "oz"));
            let knife = task.is_some_and(|t| BOARD_TASKS.contains(&t));
            if (by_weight && (produce || knife))
                || (knife && p.unit.as_deref().is_some_and(|u| PIECES.contains(&u)))
                || (knife && p.unit.is_none() && p.quantity.is_some())
            {
                return mise_item(p, Vessel::Board, None, task.map(str::to_string));
            }
            if let (Some(quantity), Some(per_unit)) = (p.quantity, per_unit) {
                let volume = p.quantity_max.unwrap_or(quantity) * per_unit;
                return mise_item(
                    p,
                    vessel_for(volume),
                    Some(volume),
                    task.map(str::to_string),
                );
            }
            if produce || cut.is_some() {
                return mise_item(p, Vessel::Board, None, task.map(str::to_string));
            }
            if let Some(quantity) = p.quantity {
                let count = p.quantity_max.unwrap_or(quantity);
                let vessel = if count <= 2.0 {
                    Vessel::Small
                } else {
                    Vessel::Medium
                };
                return mise_item(p, vessel, None, task.map(str::to_string));
            }
            mise_item(p, Vessel::Jar, None, task.map(str::to_string))
        })
        .collect()
}

// ─── Timers ────────────────────────────────────────────────────────────────

/// The shortest timer: ten seconds.
pub const TIMER_MIN: u32 = 10;
/// The longest timer: a day.
pub const TIMER_MAX: u32 = 24 * 3600;
/// What "Set a timer" starts from on a step that mentions no time.
pub const TIMER_DEFAULT: u32 = 5 * 60;

fn number_word(word: &str) -> f64 {
    match word {
        "a" | "an" | "one" => 1.0,
        "two" => 2.0,
        "three" => 3.0,
        "four" => 4.0,
        "five" => 5.0,
        "six" => 6.0,
        "seven" => 7.0,
        "eight" => 8.0,
        "nine" => 9.0,
        "ten" => 10.0,
        "eleven" => 11.0,
        "twelve" => 12.0,
        "thirteen" => 13.0,
        "fourteen" => 14.0,
        "fifteen" => 15.0,
        "sixteen" => 16.0,
        "seventeen" => 17.0,
        "eighteen" => 18.0,
        "nineteen" => 19.0,
        "twenty" => 20.0,
        "thirty" => 30.0,
        "forty" => 40.0,
        "fifty" => 50.0,
        "sixty" => 60.0,
        "ninety" => 90.0,
        _ => 0.0,
    }
}

// A number in a step, as digits ("1 1/2", "2.5", "1½") or words ("three", "twenty-five",
// "a couple of", "half an"), optionally "and a half". The same pattern as the TS
// `findTimers` in web/src/lib/ingredients.ts.
const ONES: &str = "one|two|three|four|five|six|seven|eight|nine";
static TIME_NUMBER: LazyLock<String> = LazyLock::new(|| {
    let word = format!(
        r"(?-u:\b)(?:(?:twenty|thirty|forty|fifty|sixty|ninety)(?:[\s-](?:{ONES}))?|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen|seventeen|eighteen|nineteen|{ONES}|a\s+couple(?:\s+of)?|half\s+an?|an?)"
    );
    format!(
        r"(?:(?:[0-9]+\s+[0-9]+/[0-9]+|[0-9]+/[0-9]+|[0-9]*\.[0-9]+|[0-9]+(?:\s*[¼½¾⅓⅔⅕⅙⅚⅛⅜⅝⅞])?|[¼½¾⅓⅔⅕⅙⅚⅛⅜⅝⅞]|{word})(?:\s+and\s+a\s+half)?)"
    )
});
const TIME_UNIT: &str = r"(?:hours?|hrs?|h|minutes?|mins?|m|seconds?|secs?)(?-u:\b)";
// "25–30 minutes", "15 more minutes", "an hour and a half"
static TIME: LazyLock<Regex> = LazyLock::new(|| {
    let n = TIME_NUMBER.as_str();
    Regex::new(&format!(
        r"(?i)({n})(?:\s*(?:-|–|—|to|or)\s*({n}))?(?:\s+(?:more|additional|extra|further))?\s*({TIME_UNIT})(\s+and\s+a\s+half(?-u:\b))?"
    ))
    .unwrap()
});
// The smaller part of "1 hour 40 minutes" or "2 minutes, 30 seconds", right after the first
static TIME_REST: LazyLock<Regex> = LazyLock::new(|| {
    let n = TIME_NUMBER.as_str();
    Regex::new(&format!(r"(?i)^,?\s*(?:and\s+)?({n})\s*({TIME_UNIT})")).unwrap()
});

fn time_number(text: &str) -> Option<f64> {
    let lower = text.to_lowercase();
    let mut t = lower.split_whitespace().collect::<Vec<_>>().join(" ");
    let mut half = 0.0;
    if let Some(rest) = t.strip_suffix(" and a half") {
        half = 0.5;
        t = rest.to_string();
    }
    let n = if t.starts_with("half ") {
        Some(0.5)
    } else if t.starts_with("a couple") {
        Some(2.0)
    } else if t.starts_with(|c: char| c.is_ascii_lowercase()) {
        Some(t.split([' ', '-']).map(number_word).sum())
    } else {
        parse_number(&t)
    };
    n.map(|n| n + half)
}

fn unit_seconds(unit: &str) -> f64 {
    match unit.to_lowercase().chars().next() {
        Some('h') => 3600.0,
        Some('s') => 1.0,
        _ => 60.0,
    }
}

fn has_digit(text: &str) -> bool {
    text.chars()
        .any(|c| c.is_ascii_digit() || unicode_fraction(c).is_some())
}

/// Finds durations in a step ("bake 25–30 minutes", "1 hour 40 minutes", "three to four
/// minutes", "an hour and a half"). A range counts as its longer end.
pub fn find_timers(step: &str) -> Vec<Timer> {
    let mut out = Vec::new();
    let mut at = 0;
    while let Some(c) = TIME.captures_at(step, at) {
        let whole = c.get(0).unwrap();
        at = whole.end();
        let number = c.get(2).or_else(|| c.get(1)).unwrap().as_str();
        let unit = &c[3];
        // "h" and "m" only after digits: "a M&M" isn't a minute
        if unit.len() == 1 && !has_digit(number) {
            continue;
        }
        let Some(value) = time_number(number) else {
            continue;
        };
        let mult = unit_seconds(unit);
        let half = c.get(4).is_some();
        let mut seconds = (value + if half { 0.5 } else { 0.0 }) * mult;
        let mut label = whole.as_str().to_string();
        // "1 hour 40 minutes": a smaller unit right after joins this time
        if !half
            && let Some(rest) = TIME_REST.captures(&step[at..])
            && unit_seconds(&rest[2]) < mult
            && (rest[2].len() > 1 || has_digit(&rest[1]))
            && let Some(more) = time_number(&rest[1])
        {
            seconds += more * unit_seconds(&rest[2]);
            label.push_str(&rest[0]);
            at += rest[0].len();
        }
        let seconds = seconds.round();
        if (f64::from(TIMER_MIN)..=f64::from(TIMER_MAX)).contains(&seconds) {
            out.push(Timer {
                label: label.trim().to_string(),
                seconds: seconds as u32,
            });
        }
    }
    out
}

/// A step's timer choices, one per length: the first is the one cook mode suggests.
pub fn suggest_timers(step: &str) -> Vec<Timer> {
    let mut out: Vec<Timer> = Vec::new();
    for t in find_timers(step) {
        if !out.iter().any(|u| u.seconds == t.seconds) {
            out.push(t);
        }
    }
    out
}

/// One tap longer or shorter: 15 seconds under a minute, a minute to half an hour, 5 minutes
/// to two hours, then 15, landing on whole steps ("4 min 30 sec" goes to 5, then 6).
pub fn nudge_timer(seconds: u32, longer: bool) -> u32 {
    let from = if longer {
        seconds
    } else {
        seconds.saturating_sub(1)
    };
    let step = match from {
        0..60 => 15,
        60..1800 => 60,
        1800..7200 => 300,
        _ => 900,
    };
    let next = if longer {
        seconds / step * step + step
    } else {
        seconds.div_ceil(step) * step - step
    };
    next.clamp(TIMER_MIN, TIMER_MAX)
}

/// A length the cook typed in minutes, kept within a timer's range; `None` if it isn't one.
pub fn timer_from_minutes(minutes: f64) -> Option<u32> {
    if !minutes.is_finite() || minutes <= 0.0 {
        return None;
    }
    Some(((minutes * 60.0).round() as u32).clamp(TIMER_MIN, TIMER_MAX))
}

/// A timer's length in words: "1 hr 30 min", "45 sec".
pub fn timer_words(seconds: u32) -> String {
    let (h, m, s) = (seconds / 3600, seconds % 3600 / 60, seconds % 60);
    let parts: Vec<String> = [(h, "hr"), (m, "min"), (s, "sec")]
        .into_iter()
        .filter(|(n, _)| *n > 0)
        .map(|(n, unit)| format!("{n} {unit}"))
        .collect();
    if parts.is_empty() {
        "0 sec".to_string()
    } else {
        parts.join(" ")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_plain_and_range_quantities() {
        let p = parse_ingredient("1 1/2 cups flour, sifted");
        assert_eq!(p.quantity, Some(1.5));
        assert_eq!(p.unit.as_deref(), Some("cup"));
        assert_eq!(p.name, "flour");
        assert_eq!(p.prep.as_deref(), Some("sifted"));

        let r = parse_ingredient("2-3 cloves garlic");
        assert_eq!(r.quantity, Some(2.0));
        assert_eq!(r.quantity_max, Some(3.0));
        assert_eq!(r.unit.as_deref(), Some("clove"));
        assert_eq!(r.name, "garlic");
    }

    #[test]
    fn unit_aliases_are_case_sensitive() {
        assert_eq!(parse_ingredient("1 t salt").unit.as_deref(), Some("tsp"));
        assert_eq!(parse_ingredient("1 T butter").unit.as_deref(), Some("tbsp"));
        // Uppercase multi-letter aliases aren't in the table, so no unit.
        assert_eq!(
            parse_ingredient("1 TSP vanilla").unit.as_deref(),
            Some("tsp")
        );
    }

    #[test]
    fn reads_word_quantities() {
        let pinch = parse_ingredient("a pinch of salt");
        assert_eq!(pinch.quantity, Some(1.0));
        assert_eq!(pinch.unit.as_deref(), Some("pinch"));
        assert_eq!(pinch.name, "salt");
        // "a" wins the alternation, so "a few" is a quantity of one with the rest as the name.
        let few = parse_ingredient("a few sprigs thyme");
        assert_eq!(few.quantity, Some(1.0));
        assert_eq!(few.unit, None);
        assert_eq!(few.name, "few sprigs thyme");
        // "some" carries no number.
        assert_eq!(parse_ingredient("some parsley").quantity, None);
    }

    #[test]
    fn strips_bullets_and_splits_parenthetical_prep() {
        assert_eq!(parse_ingredient("▢ 1 cup rice").name, "rice");
        let can = parse_ingredient("1 (14 oz) can diced tomatoes");
        assert_eq!(can.unit.as_deref(), Some("can"));
        assert_eq!(can.name, "diced tomatoes");
        assert_eq!(can.prep.as_deref(), Some("14 oz"));
    }

    #[test]
    fn parses_numbers_including_unicode_fractions() {
        assert_eq!(parse_number("1 1/2"), Some(1.5));
        assert_eq!(parse_number("1½"), Some(1.5));
        assert_eq!(parse_number(".5"), Some(0.5));
        assert_eq!(parse_number("1/0"), None);
        assert_eq!(parse_number("3-4"), None);
        assert_eq!(parse_number("abc"), None);
    }

    #[test]
    fn formats_quantities_as_fractions_and_decimals() {
        assert_eq!(format_quantity(0.5), "½");
        assert_eq!(format_quantity(1.5), "1 ½");
        assert_eq!(format_quantity(1.0 / 3.0), "⅓");
        assert_eq!(format_quantity(2.675), "2 ⅔");
        assert_eq!(format_quantity(0.1), "0.1");
        assert_eq!(format_quantity(12.5), "13");
        assert_eq!(format_quantity(100.0), "100");
    }

    #[test]
    fn scales_leading_quantity_only() {
        assert_eq!(scale_ingredient("2 cups flour", 2.0), "4 cups flour");
        assert_eq!(
            scale_ingredient("1 1/2 cups flour, sifted", 2.0),
            "3 cups flour, sifted"
        );
        assert_eq!(
            scale_ingredient("2-3 cloves garlic", 2.0),
            "4-6 cloves garlic"
        );
        assert_eq!(scale_ingredient("2 cups flour", 1.0), "2 cups flour");
    }

    #[test]
    fn pluralizes_countable_units() {
        assert_eq!(plural_unit("clove", 3.0), "cloves");
        assert_eq!(plural_unit("pinch", 2.0), "pinches");
        assert_eq!(plural_unit("cup", 1.0), "cup");
        assert_eq!(plural_unit("g", 500.0), "g");
    }

    #[test]
    fn finds_timers_and_ignores_plain_words() {
        assert_eq!(
            find_timers("Simmer for 20 minutes."),
            vec![Timer {
                label: "20 minutes".to_string(),
                seconds: 1200
            }]
        );
        assert_eq!(find_timers("Chill overnight"), Vec::new());
        assert_eq!(find_timers("Boil 10–12 min")[0].seconds, 720);
    }

    #[test]
    fn mise_en_place_picks_vessels() {
        let items = mise_en_place(&[
            "1/2 tsp salt",
            "2 cups flour",
            "500 g chicken thighs, diced",
        ]);
        assert_eq!(items[0].vessel, Vessel::Pinch);
        assert_eq!(items[1].vessel, Vessel::Medium);
        assert_eq!(items[1].volume, Some(480.0));
        assert_eq!(items[2].vessel, Vessel::Board);
        assert_eq!(items[2].task.as_deref(), Some("dice"));
    }
}
